### ISSUE TITLE
Naming Kotlin files

### ISSUE THREAD

**Issue by matklad** [yole/kotlin-style-guide#36]
If a Kotlin file contains some primary class `Foo`, then it should be named `Foo.kt`.

But what should be  the name of file which does not contain a single main class?

**Comment by matklad** [comment]
Use names like `FooBarUtils.kt`,  to be consistent with other files.

**Comment by matklad** [comment]
Use names like `fooBarUtils.kt` to show that this file does not correspond to a single class.

**Comment by cbruegg** [comment]
@matklad `FooBarUtils.kt`, since from the Java-side it looks like `FooBarUtilsKt` and `fooBarUtilsKt` would be an unusual class name.

**Comment by damianw** [comment]
I prefer the plural name of the class instead of utils, e.g. `Foos.kt`. If the file is meant to be accessible from Java, it should have a `@file:JvmName("Foos")` annotation.

**Comment by kevinmost** [comment]
Name the file `FooBarUtils.kt`, and add `@file:JvmName("FooBarUtils")` at the top of the file if it's meant to be used from Java.

**Comment by udalov** [comment]
> `FooBarUtils.kt`, since from the Java-side it looks like `FooBarUtilsKt` and `fooBarUtilsKt` would be an unusual class name.

Names of file classes generated by kotlinc are capitalized, so a class file generated for `fooBarUtils.kt` will still be visible as `FooBarUtilsKt` in Java.

**Comment by yole** [comment]
The current style guide says that names should be capitalized (and also that you shouldn't use meaningless words such as `Util` as part of class names).
