### ISSUE TITLE
Tabs and indents

### ISSUE THREAD

**Issue by douglarek** [yole/kotlin-style-guide#38]
Should Kotlin use `tab size 2, indent 2, continuation indent 4` code style like Scala? And Google java style keeps this too .

**Comment by bjartek** [comment]
+1

**Comment by yole** [comment]
No, it should use tab size 4, indent 4 and continuation indent 8, as in the Java style guide.

**Comment by douglarek** [comment]
@yole Java style guide ?  is it http://www.oracle.com/technetwork/java/codeconventions-150003.pdf? 

```
4 - Indentation
Four spaces should be used as the unit of indentation. The exact construction of the indentation
(spaces vs. tabs) is unspecified. Tabs must be set exactly every 8 spaces (not 4).
```

**Comment by yole** [comment]
Yes

**Comment by napperley** [comment]
Both the Java ([unofficial](http://www.oracle.com/technetwork/java/codeconventions-150003.pdf)) and [Google Style](https://google.github.io/styleguide/javaguide.html) guides provide inadequate/confusing guidance on indentation. A simpler approach is to use 4 spaces for indentation using soft tabs (tabs converted to spaces) only. Tabs (hard tabs) are highly problematic since they correspond to different spaces in every text editor/IDE.

Does IntelliJ for example use soft tabs by default?

**Comment by yole** [comment]
Yes, IntelliJ uses soft tabs by default.

**Comment by ZakTaccardi** [comment]
4/4/8 + 100 line column break makes for terrible readability.

2/2/4 with 120 char column width is just functionally better. Especially as you begin to nest function calls with Kotlin or RxJava.

This is a very unfortunate decision.

**Comment by ZakTaccardi** [comment]
This was a very good opportunity to improve this situation for the community :-\

**Comment by JakeWharton** [comment]
Continuation is not 8 it's 4

**Comment by ZakTaccardi** [comment]
I just pulled the EAP Kotlin formatter from the plugin, and it had the indent set to 4/4/8. Maybe it hasn't been updated yet?

I'm a little bitter after reformatting a bunch of code from 2/2/4 (120) to 4/4/8 (100). Sometimes it's hard to let go!

@jakewharton where does that leave the [Android Style Guide](https://android.github.io/kotlin-guides/style.html#continuation-indent)? Will it be updated to 4/4/4?

**Comment by JakeWharton** [comment]
Yes.

**Comment by yole** [comment]
In our style guide, the continuation indent is still 8, but many places which previously used continuation indent have now been switched to normal indent.

Also, our style guide does not have any line length limit.
