### ISSUE TITLE
Add a note on return types in public APIs

### ISSUE THREAD

**Issue by abreslav** [yole/kotlin-style-guide#42]
Stable public APIs should declare return types of functions and properties explicitly, and not infer them from bodies, because subtle changes in the implementation code or improvements in the language may result in changing of the ABI that won't be obvious from the source code.

**Comment by voddan** [comment]
This should be a part of the "library mode" and enforced by the compiler

**Comment by mikehearn** [comment]
We solve this in Corda by having a tool integrated with TeamCity that verifies there are no ABI changes in our public API, but a style guide rule would be useful too.

**Comment by yole** [comment]
This is included in the current draft of the style guide.
